import '../globals.css';

export const metadata = {
  title: 'Fit77',
  description: 'Generated by Next + Sanity',
};

const RootLayout = ({ children }) => (
  <html lang="uk">
    <body>{children}</body>
  </html>
);

export default RootLayout;
