import '../globals.css';

export const metadata = {
  title: 'Fit77',
  description: 'Generated by Next + Sanity',
};

function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;
