import '../globals.css';
import './styles/main.scss';
import Header from './sections/header';
// import Footer from './sections/footer';

export const metadata = {
  title: 'Fit77',
  description: 'Generated by Next + Sanity',
};

const RootLayout = ({ children }) => (
  <html lang="uk">
    <body>
      <Header />

      <main>
        {children}
      </main>

      {/* <Footer /> */}
    </body>
  </html>
);

export default RootLayout;
